language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install: pip install requests
script:
  - python ./nessrest/test_ness6rest.py
  - python setup.py sdist
  - python setup.py bdist_wheel
  - python setup.py test
